### ISSUE TITLE
怎么获取当前的登录用户

### ISSUE THREAD

**Issue by guowenzhuang** [duyleduc/spring-boot-webflux-security#1]
请问我要获取当前的登录用户应该怎么做

**Comment by duyleduc** [comment]
Hello, could you write it in English, I don't know Chinese ?

**Comment by guowenzhuang** [comment]
Excuse me, what should I do if I need oauth

**Comment by duyleduc** [comment]
Hello, please take a look at DemoController, you could actually get username from a rest api. You could test it with Postman

**Comment by guowenzhuang** [comment]
ok
